apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "hello-app"
  name: "hello-svc-nodeport"
spec:
  ports:
    - port: 9096
      protocol: "TCP"
      targetPort: 9096
      nodePort: 30007
  selector:
    app: "hello-app"
  type: "NodePort"
